### ISSUE TITLE
step-by-step instructions do not have a step for indexing rRNA

### ISSUE THREAD

**Issue by monachristensen** [vondoRishi/4-RNA-seq#5]
step-by-step instructions do not have a step for indexing rRNA

**Comment by sqianglan** [comment]
In the scripts of sortmerna.sh,  there is one step '# source scripts/sortMeRNA_indexdb.sh' has been commented. just remove the '#' sign. 
Then It should automatically run the indexdb.sh script when you run sortmerna.sh for indexing.

**Comment by vondoRishi** [comment]
@sqianglan I will update 4-rna-seq with new features very soon, may be tomorrow. Then **sortMeRNA_indexdb.sh** will be executed separately. 
@monachristensen thanks for reporting this, I will update the instructions soon.

**Comment by vondoRishi** [comment]
Instructions are updated now.
