### ISSUE TITLE
salmon.sh first run error

### ISSUE THREAD

**Issue by sqianglan** [vondoRishi/4-RNA-seq#6]
Hi, 
 I have tried to run the Salmon.sh from sortmeRNA results. 
In the first run, the index job has been assigned , but the main bash work has been failed immediately after indexing initiated. 
So I run the salmon.sh again after indexing has been done, the salmon job is allocated to different nodes, but another failure message has been sent to my email. 
Is it possible to ask the script to initiate the next step only after the previous one finished like you have done in the pipeline.sh?

**Comment by vondoRishi** [comment]
With the latest script, it is working fine. Please open this again if the problem appears again.
